"""Tests for the digest-verifying Chromium pre-seeder.

scripts/ci/install_chromium.py is the write-capable jobs' only path to an
executing browser: it must refuse an archive whose digest does not match the
committed table, refuse to trust a browser directory it did not verify
itself, and fail loudly when playwright re-downloads anything anyway. The
cases below pin the registry resolution (revision/browserVersion/digest,
trust-on-first-use recipe on a miss), the URL templates, the streaming
downloader's mirror fallback, the extractor's refusals (symlink entries,
zip-slip) and its owner-only mode mask, the seed/replace/skip lifecycle around the
DIGEST_VERIFIED provenance marker, the no-re-download assertion, and the
CLI's exit codes. No test touches the network: downloads are file:// URLs
of local files or a stubbed download_archive.
"""
from __future__ import annotations

import hashlib
import importlib.machinery
import json
import os
import shutil
import sys
import zipfile
from pathlib import Path
from types import SimpleNamespace

import pytest

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "scripts" / "ci"))

import install_chromium  # noqa: E402  # pylint: disable=wrong-import-position

REVISION = "1243"
BROWSER_VERSION = "153.0.8010.12"
FFMPEG_REVISION = "1011"

# A browsers.json shaped like playwright 1.63.0's (plus entries the script
# must ignore), with the revisions the tests' digests are keyed by.
BROWSERS_JSON = {
    "comment": "DO NOT EDIT — generated by playwright",
    "browsers": [
        {"name": "chromium", "revision": REVISION,
         "installByDefault": True, "browserVersion": BROWSER_VERSION,
         "title": "Chrome for Testing"},
        {"name": "chromium-headless-shell", "revision": REVISION,
         "installByDefault": True, "browserVersion": BROWSER_VERSION,
         "title": "Chrome Headless Shell"},
        {"name": "firefox", "revision": "1543",
         "installByDefault": True, "browserVersion": "155.0"},
        {"name": "ffmpeg", "revision": FFMPEG_REVISION,
         "installByDefault": True},
        {"name": "winldd", "revision": "1007", "installByDefault": False},
    ],
}

# The on-disk directory names playwright uses, observed 2026-09-29 (note the
# headless shell's underscore where the registry name has a hyphen).
DIR_NAMES = {
    "chromium": f"chromium-{REVISION}",
    "chromium-headless-shell": f"chromium_headless_shell-{REVISION}",
    "ffmpeg": f"ffmpeg-{FFMPEG_REVISION}",
}


# --- helpers ------------------------------------------------------------

def registry():
    """The fixture browsers.json as build_products consumes it."""
    return {entry["name"]: entry for entry in BROWSERS_JSON["browsers"]}


def products(digests):
    return install_chromium.build_products(registry(), digests)


def write_zip(path: Path, entries) -> Path:
    """Build a real zip with unix modes, like playwright's archives."""
    with zipfile.ZipFile(path, "w") as archive:
        for name, data, mode in entries:
            info = zipfile.ZipInfo(name)
            is_dir = name.endswith("/")
            info.external_attr = (0o40755 << 16) | 0x10 if is_dir \
                else mode << 16
            archive.writestr(info, data)
    return path


def inodes_of(root: Path, seeded) -> dict:
    return {
        install_chromium.install_dir(root, product).name:
        install_chromium.install_dir(root, product).stat().st_ino
        for product in seeded
    }


def _sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def patch_spec(monkeypatch, fake_spec):
    monkeypatch.setattr(install_chromium, "find_playwright_spec",
                        lambda: fake_spec)


# --- fixtures -----------------------------------------------------------

@pytest.fixture(name="registry_root")
def fixture_registry_root(tmp_path: Path) -> Path:
    """A fake playwright package root carrying the fixture browsers.json."""
    package = tmp_path / "playwright" / "driver" / "package"
    package.mkdir(parents=True)
    (package / "browsers.json").write_text(
        json.dumps(BROWSERS_JSON), encoding="utf-8")
    return tmp_path / "playwright"


@pytest.fixture(name="fake_spec")
def fixture_fake_spec(registry_root: Path):
    """Route find_browsers_json at the fixture package root."""
    spec = importlib.machinery.ModuleSpec("playwright", None)  # type: ignore[arg-type]
    spec.submodule_search_locations = [str(registry_root)]
    return spec


@pytest.fixture(name="archives")
def fixture_archives(tmp_path: Path) -> dict:
    """The three archives, laid out exactly as the real ones were observed.

    chromium and the headless shell extract one top-level directory (the
    executable inside it); ffmpeg extracts loose files.
    """
    base = tmp_path / "archives"
    base.mkdir()
    zips = {
        "chromium": write_zip(base / "chrome-linux64.zip", [
            ("chrome-linux64/", b"", 0),
            ("chrome-linux64/chrome", b"#!/bin/sh\nexec real-chrome\n",
             0o755),
            ("chrome-linux64/ABOUT", b"chrome\n", 0o644),
            ("chrome-linux64/MEIPreload/manifest.json", b"{}\n", 0o644),
        ]),
        "chromium-headless-shell": write_zip(
            base / "chrome-headless-shell-linux64.zip", [
                ("chrome-headless-shell-linux64/", b"", 0),
                ("chrome-headless-shell-linux64/chrome-headless-shell",
                 b"#!/bin/sh\nexec real-shell\n", 0o755),
            ]),
        "ffmpeg": write_zip(base / "ffmpeg-linux.zip", [
            ("ffmpeg-linux", b"#!/bin/sh\nexec real-ffmpeg\n", 0o755),
            ("COPYING.LGPLv2.1", b"LGPL text\n", 0o644),
        ]),
    }
    return {
        name: {"path": path, "sha256": _sha256(path)}
        for name, path in zips.items()
    }


@pytest.fixture(name="digests")
def fixture_digests(archives) -> dict:
    """The digest table the tests run against (patched over DIGESTS)."""
    return {
        ("chromium", REVISION): archives["chromium"]["sha256"],
        ("chromium-headless-shell", REVISION):
            archives["chromium-headless-shell"]["sha256"],
        ("ffmpeg", FFMPEG_REVISION): archives["ffmpeg"]["sha256"],
    }


@pytest.fixture(name="browsers_root")
def fixture_browsers_root(tmp_path: Path, monkeypatch) -> Path:
    """Isolate the browsers directory through the same env var playwright
    itself honours, so the tests never touch ~/.cache."""
    root = tmp_path / "browsers"
    monkeypatch.setenv("PLAYWRIGHT_BROWSERS_PATH", str(root))
    return root


@pytest.fixture(name="stub_downloads")
def fixture_stub_downloads(monkeypatch, archives):
    """Replace download_archive with a local-file copy of the fixture zip.

    Records the urls it was asked for so tests can pin the mirror order.
    """
    calls = []

    def fake_download(urls, destination, label, timeout=0):
        assert timeout == install_chromium.DOWNLOAD_TIMEOUT
        calls.append(list(urls))
        shutil.copyfile(archives[label]["path"], destination)
        return (archives[label]["sha256"],
                archives[label]["path"].stat().st_size)

    monkeypatch.setattr(install_chromium, "download_archive", fake_download)
    return calls


# --- registry resolution ------------------------------------------------

def test_build_products_resolves_revision_digest_and_urls(digests):
    seeded = products(digests)
    by_name = {product.spec.name: product for product in seeded}
    assert [product.spec.name for product in seeded] == [
        "chromium", "chromium-headless-shell", "ffmpeg"]
    assert by_name["chromium"].revision == REVISION
    assert by_name["chromium"].browser_version == BROWSER_VERSION
    assert by_name["chromium"].digest == digests[("chromium", REVISION)]
    assert by_name["ffmpeg"].browser_version is None
    assert install_chromium.archive_urls(by_name["chromium"]) == [
        "https://cdn.playwright.dev/builds/cft/153.0.8010.12/linux64/"
        "chrome-linux64.zip"]
    assert install_chromium.archive_urls(by_name["chromium-headless-shell"]) \
        == ["https://cdn.playwright.dev/builds/cft/153.0.8010.12/linux64/"
            "chrome-headless-shell-linux64.zip"]
    assert install_chromium.archive_urls(by_name["ffmpeg"]) == [
        "https://cdn.playwright.dev/builds/ffmpeg/1011/ffmpeg-linux.zip",
        "https://playwright.download.prss.microsoft.com/builds/ffmpeg/1011/"
        "ffmpeg-linux.zip",
    ]


def test_build_products_digest_miss_is_trust_on_first_use(digests):
    reduced = dict(digests)
    del reduced[("chromium", REVISION)]
    with pytest.raises(install_chromium.InstallError) as raised:
        install_chromium.build_products(registry(), reduced)
    message = str(raised.value)
    # the recipe: where the row goes, the revision to key it by, the URL to
    # hash, and the refusal to download anything until it lands
    assert f'("chromium", "{REVISION}")' in message
    assert "builds/cft/153.0.8010.12/linux64/chrome-linux64.zip" in message
    assert "sha256sum" in message
    assert "DIGESTS" in message
    assert "Nothing is downloaded" in message


def test_build_products_unknown_registry_entry(digests):
    with pytest.raises(install_chromium.InstallError, match="no 'ffmpeg'"):
        install_chromium.build_products(
            {name: registry()[name]
             for name in ("chromium", "chromium-headless-shell")},
            digests)


def test_build_products_missing_revision(digests):
    with pytest.raises(install_chromium.InstallError, match="no revision"):
        install_chromium.build_products({"chromium": {}}, digests)


def test_build_products_missing_browser_version(digests):
    entries = {name: {"revision": REVISION}
               for name in ("chromium", "chromium-headless-shell")}
    entries["chromium-headless-shell"]["browserVersion"] = BROWSER_VERSION
    entries["ffmpeg"] = {"revision": FFMPEG_REVISION}
    with pytest.raises(install_chromium.InstallError,
                       match="no browserVersion"):
        install_chromium.build_products(entries, digests)


def test_load_registry_missing_file(tmp_path):
    with pytest.raises(install_chromium.InstallError, match="cannot read"):
        install_chromium.load_registry(tmp_path / "absent.json")


def test_load_registry_rejects_shape_changes(tmp_path):
    bad = tmp_path / "browsers.json"
    bad.write_text(json.dumps({"browsers": "gone"}), encoding="utf-8")
    with pytest.raises(install_chromium.InstallError, match="'browsers'"):
        install_chromium.load_registry(bad)
    bad.write_text(json.dumps({"browsers": [{"noName": 1}]}),
                   encoding="utf-8")
    with pytest.raises(install_chromium.InstallError, match="has no name"):
        install_chromium.load_registry(bad)


def test_find_browsers_json_without_playwright(monkeypatch):
    monkeypatch.setattr(install_chromium, "find_playwright_spec",
                        lambda: None)
    with pytest.raises(install_chromium.InstallError,
                       match="not importable"):
        install_chromium.find_browsers_json()


def test_find_browsers_json_unexpected_layout(fake_spec, registry_root,
                                              monkeypatch):
    monkeypatch.setattr(install_chromium, "find_playwright_spec",
                        lambda: fake_spec)
    (registry_root / "driver" / "package" / "browsers.json").unlink()
    with pytest.raises(install_chromium.InstallError, match="browsers.json"):
        install_chromium.find_browsers_json()


# --- browsers root ------------------------------------------------------

def test_browsers_root_prefers_the_env_var(monkeypatch, tmp_path):
    monkeypatch.setenv("PLAYWRIGHT_BROWSERS_PATH", str(tmp_path))
    assert install_chromium.browsers_root() == tmp_path


def test_browsers_root_uses_xdg_cache(monkeypatch, tmp_path):
    monkeypatch.delenv("PLAYWRIGHT_BROWSERS_PATH", raising=False)
    monkeypatch.setenv("XDG_CACHE_HOME", str(tmp_path))
    assert install_chromium.browsers_root() == tmp_path / "ms-playwright"


def test_browsers_root_defaults_home(monkeypatch):
    monkeypatch.delenv("PLAYWRIGHT_BROWSERS_PATH", raising=False)
    monkeypatch.delenv("XDG_CACHE_HOME", raising=False)
    assert install_chromium.browsers_root() \
        == Path.home() / ".cache" / "ms-playwright"


# --- download -----------------------------------------------------------

def test_download_archive_streams_and_hashes(tmp_path):
    payload = b"x" * (3 * install_chromium.CHUNK + 1234)
    source = tmp_path / "payload.bin"
    source.write_bytes(payload)
    digest, size = install_chromium.download_archive(
        [source.as_uri()], tmp_path / "out.bin", "chromium")
    assert digest == hashlib.sha256(payload).hexdigest()
    assert size == len(payload)
    assert (tmp_path / "out.bin").read_bytes() == payload


def test_download_archive_falls_back_to_the_next_mirror(tmp_path):
    good = tmp_path / "good.bin"
    good.write_bytes(b"verified bytes")
    digest, size = install_chromium.download_archive(
        [(tmp_path / "absent.bin").as_uri(), good.as_uri()],
        tmp_path / "out.bin", "ffmpeg")
    assert digest == _sha256(good)
    assert size == len(b"verified bytes")


def test_download_archive_all_mirrors_fail(tmp_path):
    with pytest.raises(install_chromium.InstallError, match="every "
                                                            "download"):
        install_chromium.download_archive(
            [(tmp_path / "absent-a.bin").as_uri(),
             (tmp_path / "absent-b.bin").as_uri()],
            tmp_path / "out.bin", "chromium")


# --- extraction ---------------------------------------------------------

def test_extract_archive_extracts_content_and_nesting(tmp_path):
    # Runs on every OS: what lands on disk is the archive's bytes, nested
    # as stored — the mode questions live in the test below.
    archive = write_zip(tmp_path / "a.zip", [
        ("top/", b"", 0),
        ("top/bin", b"binary", 0o755),
        ("top/dir/nested.txt", b"text", 0o644),
    ])
    destination = tmp_path / "out"
    install_chromium.extract_archive(archive, destination)
    assert (destination / "top" / "bin").read_bytes() == b"binary"
    assert (destination / "top" / "dir" / "nested.txt") \
        .read_bytes() == b"text"


@pytest.mark.skipif(os.name == "nt",
                    reason="mode semantics are POSIX-only and the browser "
                           "consumers are ubuntu-latest")
def test_extract_archive_modes_mask_world_bits(tmp_path):
    # Extraction fidelity, modulo the owner-only mask: the extractor honors
    # the archive's unix modes with everything past the owner bits stripped
    # (CodeQL py/overly-permissive-file flags group bits too), so a 0755
    # entry lands 0700 and a 0644 entry lands 0600.
    archive = write_zip(tmp_path / "a.zip", [
        ("top/", b"", 0),
        ("top/bin", b"binary", 0o755),
        ("top/dir/nested.txt", b"text", 0o644),
    ])
    destination = tmp_path / "out"
    install_chromium.extract_archive(archive, destination)
    assert (destination / "top" / "bin").stat().st_mode & 0o777 == 0o700
    assert (destination / "top" / "dir" / "nested.txt") \
        .stat().st_mode & 0o777 == 0o600


def test_extract_archive_refuses_symlink_entries(tmp_path):
    archive = write_zip(tmp_path / "link.zip", [
        ("top/bin", b"binary", 0o755),
    ])
    forged = zipfile.ZipInfo("top/evil")
    forged.external_attr = 0o120777 << 16
    with zipfile.ZipFile(archive, "a") as appended:
        appended.writestr(forged, b"../../target")
    with pytest.raises(install_chromium.InstallError, match="symlink"):
        install_chromium.extract_archive(archive, tmp_path / "out")


def test_extract_archive_refuses_zip_slip(tmp_path):
    for evil in ("../evil", "/abs/evil"):
        archive = write_zip(tmp_path / "slip.zip", [
            ("top/bin", b"binary", 0o755),
        ])
        with zipfile.ZipFile(archive, "a") as appended:
            appended.writestr(zipfile.ZipInfo(evil), b"escaped")
        with pytest.raises(install_chromium.InstallError,
                           match="escapes"):
            install_chromium.extract_archive(archive, tmp_path / "out")


def test_extract_archive_bad_zip_cleans_up(tmp_path):
    archive = tmp_path / "garbage.zip"
    archive.write_bytes(b"not a zip at all")
    destination = tmp_path / "out"
    destination.mkdir()
    with pytest.raises(install_chromium.InstallError, match="extracting"):
        install_chromium.extract_archive(archive, destination)
    assert not destination.exists()


# --- seeding ------------------------------------------------------------

def test_seed_product_downloads_verifies_and_marks(browsers_root, digests,
                                                   stub_downloads):
    chromium = products(digests)[0]
    outcome = install_chromium.seed_product(browsers_root, chromium)
    assert outcome == "downloaded"
    product_dir = install_chromium.install_dir(browsers_root, chromium)
    assert (product_dir / "chrome-linux64" / "chrome").read_bytes() \
        .startswith(b"#!/bin/sh")
    assert (product_dir / "INSTALLATION_COMPLETE").exists()
    record = json.loads(
        (product_dir / "DIGEST_VERIFIED").read_text(encoding="utf-8"))
    assert record["product"] == "chromium"
    assert record["revision"] == REVISION
    assert record["sha256"] == digests[("chromium", REVISION)]
    executable = product_dir / "chrome-linux64" / "chrome"
    # Mode semantics are POSIX-only and the browser consumers are
    # ubuntu-latest: Windows reports a fixed st_mode, so the assertion is
    # meaningless there — every non-mode assertion above ran on all OSes.
    if os.name != "nt":
        assert executable.stat().st_mode & 0o111
    assert stub_downloads == [[
        "https://cdn.playwright.dev/builds/cft/153.0.8010.12/linux64/"
        "chrome-linux64.zip"]]


def test_seed_product_is_idempotent_when_verified(browsers_root, digests,
                                                  stub_downloads):
    chromium = products(digests)[0]
    install_chromium.seed_product(browsers_root, chromium)
    outcome = install_chromium.seed_product(browsers_root, chromium)
    assert outcome == "already-verified"
    assert len(stub_downloads) == 1  # the second call downloaded nothing


def test_seed_product_replaces_an_unverified_install(browsers_root,
                                                     digests,
                                                     stub_downloads):
    chromium = products(digests)[0]
    product_dir = install_chromium.install_dir(browsers_root, chromium)
    product_dir.mkdir(parents=True)
    (product_dir / "INSTALLATION_COMPLETE").write_bytes(b"")
    (product_dir / "chrome-linux64").mkdir()
    (product_dir / "chrome-linux64" / "chrome").write_bytes(b"TAMPERED")
    outcome = install_chromium.seed_product(browsers_root, chromium)
    assert outcome == "replaced-unverified"
    assert (product_dir / "chrome-linux64" / "chrome").read_bytes() \
        .startswith(b"#!/bin/sh")
    assert (product_dir / "DIGEST_VERIFIED").exists()


def test_seed_product_replaces_stale_provenance(browsers_root, digests,
                                                stub_downloads):
    chromium = products(digests)[0]
    product_dir = install_chromium.install_dir(browsers_root, chromium)
    product_dir.mkdir(parents=True)
    (product_dir / "DIGEST_VERIFIED").write_text(
        json.dumps({"sha256": "0" * 64}), encoding="utf-8")
    outcome = install_chromium.seed_product(browsers_root, chromium)
    assert outcome == "replaced-unverified"


def test_seed_product_fails_loudly_on_digest_mismatch(browsers_root,
                                                      monkeypatch,
                                                      digests):
    chromium = products(digests)[0]
    monkeypatch.setattr(
        install_chromium, "download_archive",
        lambda urls, destination, label, timeout=0: ("b" * 64, 5))
    with pytest.raises(install_chromium.InstallError) as raised:
        install_chromium.seed_product(browsers_root, chromium)
    message = str(raised.value)
    assert digests[("chromium", REVISION)] in message  # expected
    assert "b" * 64 in message                         # actual
    assert "refusing to seed or execute" in message
    product_dir = install_chromium.install_dir(browsers_root, chromium)
    assert not product_dir.exists()


def test_seed_product_fails_when_executable_missing(browsers_root,
                                                    monkeypatch, digests,
                                                    tmp_path):
    noexe = write_zip(tmp_path / "shell-noexe.zip", [
        ("chrome-headless-shell-linux64/ABOUT", b"nothing executable\n",
         0o644),
    ])
    digests = dict(digests)
    digests[("chromium-headless-shell", REVISION)] = _sha256(noexe)
    shell = products(digests)[1]

    def fake_download(urls, destination, label, timeout=0):
        shutil.copyfile(noexe, destination)
        return _sha256(noexe), noexe.stat().st_size

    monkeypatch.setattr(install_chromium, "download_archive", fake_download)
    with pytest.raises(install_chromium.InstallError,
                       match="missing or not executable"):
        install_chromium.seed_product(browsers_root, shell)
    # nothing half-seeded is left for playwright to consider installed
    assert not install_chromium.install_dir(browsers_root, shell).exists()


# --- playwright install + no-re-download assertion ----------------------

def test_run_playwright_install_spawns_the_module(monkeypatch, tmp_path):
    seen = {}

    def fake_run(command, env=None, check=False):
        seen["command"] = command
        seen["env"] = env
        seen["check"] = check
        return SimpleNamespace(returncode=0)

    monkeypatch.setattr(install_chromium.subprocess, "run", fake_run)
    install_chromium.run_playwright_install(tmp_path)
    assert seen["command"] == [sys.executable, "-m", "playwright", "install",
                               "--with-deps", "chromium"]
    assert seen["env"]["PLAYWRIGHT_BROWSERS_PATH"] == str(tmp_path)
    assert seen["check"] is False


def test_run_playwright_install_failure_is_loud(monkeypatch, tmp_path):
    monkeypatch.setattr(
        install_chromium.subprocess, "run",
        lambda command, env=None, check=False:
        SimpleNamespace(returncode=42))
    with pytest.raises(install_chromium.InstallError, match="exited 42"):
        install_chromium.run_playwright_install(tmp_path)


def test_assert_seeded_intact_tolerates_marker_writes_only(
        browsers_root, digests, stub_downloads):
    seeded = products(digests)
    for product in seeded:
        install_chromium.seed_product(browsers_root, product)
    # what playwright's install actually adds on the skip path: the deps
    # marker inside each seeded directory and the .links directory at the
    # root — none of which replaces a browser
    for product in seeded:
        product_dir = install_chromium.install_dir(browsers_root, product)
        (product_dir / "DEPENDENCIES_VALIDATED").write_bytes(b"")
    (browsers_root / ".links").mkdir()
    install_chromium.assert_seeded_intact(browsers_root, seeded,
                                          inodes_of(browsers_root, seeded))


def test_assert_seeded_intact_catches_a_replaced_directory(
        browsers_root, digests, stub_downloads):
    seeded = products(digests)
    for product in seeded:
        install_chromium.seed_product(browsers_root, product)
    inodes = inodes_of(browsers_root, seeded)
    chromium_dir = install_chromium.install_dir(browsers_root, seeded[0])
    # A re-download materializes the new directory elsewhere and moves it
    # in, so build the replacement BEFORE removing the original: both
    # directories then exist at once, and two simultaneously existing
    # directories never share an inode — the replacement's inode differs
    # from the recorded one on every filesystem. (Creating it after the
    # rmtree instead lets the filesystem hand the freed inode straight
    # back, which ext4 usually does, so this test's outcome depended on
    # the allocator state the ~400 preceding tests left behind.)
    replacement = browsers_root / "replacement"
    replacement.mkdir()
    shutil.rmtree(chromium_dir)
    replacement.rename(chromium_dir)
    with pytest.raises(install_chromium.InstallError, match="replaced"):
        install_chromium.assert_seeded_intact(browsers_root, seeded, inodes)


def test_assert_seeded_intact_catches_missing_provenance(
        browsers_root, digests, stub_downloads):
    seeded = products(digests)
    for product in seeded:
        install_chromium.seed_product(browsers_root, product)
    inodes = inodes_of(browsers_root, seeded)
    product_dir = install_chromium.install_dir(browsers_root, seeded[0])
    (product_dir / "DIGEST_VERIFIED").unlink()
    with pytest.raises(install_chromium.InstallError,
                       match="DIGEST_VERIFIED"):
        install_chromium.assert_seeded_intact(browsers_root, seeded, inodes)


def test_assert_seeded_intact_catches_an_unverified_new_directory(
        browsers_root, digests, stub_downloads):
    seeded = products(digests)
    for product in seeded:
        install_chromium.seed_product(browsers_root, product)
    inodes = inodes_of(browsers_root, seeded)
    (browsers_root / "chromium-9999").mkdir()  # playwright fetched a new one
    with pytest.raises(install_chromium.InstallError, match="chromium-9999"):
        install_chromium.assert_seeded_intact(browsers_root, seeded, inodes)


# --- CLI ----------------------------------------------------------------

def test_main_happy_path_seeds_and_runs_install(browsers_root, digests,
                                                stub_downloads, fake_spec,
                                                monkeypatch, capsys):
    monkeypatch.setattr(install_chromium, "DIGESTS", digests)
    patch_spec(monkeypatch, fake_spec)
    runs = []

    def fake_run(command, env=None, check=False):
        runs.append(command)
        return SimpleNamespace(returncode=0)

    monkeypatch.setattr(install_chromium.subprocess, "run", fake_run)
    assert install_chromium.main([]) == 0
    assert len(runs) == 1
    out = capsys.readouterr().out
    for name in ("chromium", "chromium-headless-shell", "ffmpeg"):
        assert f"{name} revision" in out
    assert "downloaded nothing" in out
    for name, dirname in DIR_NAMES.items():
        assert (browsers_root / dirname / "INSTALLATION_COMPLETE").exists()


def test_main_exit_2_on_digest_mismatch(browsers_root, digests, fake_spec,
                                        monkeypatch, capsys):
    monkeypatch.setattr(install_chromium, "DIGESTS", digests)
    patch_spec(monkeypatch, fake_spec)
    monkeypatch.setattr(
        install_chromium, "download_archive",
        lambda urls, destination, label, timeout=0: ("c" * 64, 7))
    assert install_chromium.main([]) == 2
    captured = capsys.readouterr()
    assert "expected: " in captured.err
    assert "c" * 64 in captured.err
    assert captured.out == ""


def test_main_exit_2_without_playwright(browsers_root, monkeypatch, capsys):
    monkeypatch.setattr(install_chromium, "find_playwright_spec",
                        lambda: None)
    assert install_chromium.main([]) == 2
    assert "not importable" in capsys.readouterr().err


def test_main_refuses_the_reserved_browsers_path_zero(fake_spec, monkeypatch,
                                                      capsys):
    # The playwright-reserved value "0" (package-local .local-browsers)
    # must be refused, not honoured as a literal ./0 the script verifies
    # while playwright downloads unverified browsers elsewhere.
    monkeypatch.setenv("PLAYWRIGHT_BROWSERS_PATH", "0")
    patch_spec(monkeypatch, fake_spec)
    assert install_chromium.main([]) == 2
    captured = capsys.readouterr()
    assert 'PLAYWRIGHT_BROWSERS_PATH="0"' in captured.err
    assert "reserved" in captured.err
    assert ".local-browsers" in captured.err
