name: claim
on:
  issue_comment:
    types: [created]
concurrency:
  group: claim-${{ github.event.issue.number }}
  cancel-in-progress: false
  queue: max
jobs:
  claim:
    if: >-
      github.event.comment.user.type != 'Bot'
      && (contains(github.event.comment.body, '/claim')
          || contains(github.event.comment.body, '/unclaim')
          || contains(github.event.comment.body, '/release'))
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      issues: write
    steps:
      - uses: Nitjsefnie-Actions/claim@cf2aaae56eb3bb6c655b8c4bc35906dafc77a63e # v2.0.2
        with:
          max-claims: 'read=2, triage=4, write=6, maintain=10, admin=-1'
          expire: '7'
